version: "3.8"

services:
  db:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: users
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db_data:
